[tool.poetry]
name = "ANONCOM"
version = "0.1"
description = "ANONCOM for IB."
repository = "https://github.com/Freddsle/ANONCOM/"
authors = ["Yuliya Burankova, Anna Toidze, Dmitrii Podgalo, Elena Grigoreva, Alexandra Gorbonos"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"


